import { MarketingShell } from "../_components/MarketingShell";

const INK       = "oklch(0.28 0.022 55)";
const INK_SOFT  = "oklch(0.42 0.022 60)";
const INK_MUTE  = "oklch(0.58 0.018 65)";
const LINEN     = "oklch(0.925 0.025 78)";
const LINEN_DEEP= "oklch(0.885 0.028 75)";
const RULE      = "oklch(0.80 0.025 70)";
const AEGEAN    = "oklch(0.42 0.080 200)";
const TERRA_DEEP= "oklch(0.52 0.130 38)";
const OLIVE_DEEP= "oklch(0.38 0.045 125)";
const OCHRE     = "oklch(0.75 0.090 78)";
const SERIF     = "'Cormorant Garamond', Georgia, serif";
const BODY      = "'Work Sans', ui-sans-serif, system-ui, sans-serif";
const MONO      = "'JetBrains Mono', ui-monospace, monospace";

type TagType = "new" | "improved" | "fix" | "infrastructure";

const TAG_STYLES: Record<TagType, { bg: string; color: string; label: string }> = {
  new:            { bg: AEGEAN,      color: "oklch(0.97 0.02 190)",  label: "New" },
  improved:       { bg: OLIVE_DEEP,  color: "oklch(0.97 0.02 120)",  label: "Improved" },
  fix:            { bg: TERRA_DEEP,  color: "oklch(0.97 0.02 45)",   label: "Fix" },
  infrastructure: { bg: "oklch(0.50 0.025 240)", color: "oklch(0.97 0.01 240)", label: "Infra" },
};

function Tag({ type }: { type: TagType }) {
  const s = TAG_STYLES[type];
  return (
    <span style={{ display: "inline-block", background: s.bg, color: s.color, fontFamily: MONO, fontSize: 9, letterSpacing: "0.14em", textTransform: "uppercase", padding: "3px 8px", borderRadius: 2 }}>
      {s.label}
    </span>
  );
}

interface ChangeEntry {
  tag: TagType;
  text: string;
}

interface Release {
  version: string;
  date: string;
  headline: string;
  summary?: string;
  changes: ChangeEntry[];
}

const RELEASES: Release[] = [
  {
    version: "0.9.0",
    date: "May 2026",
    headline: "Personalized morning pulse questions",
    summary: "Check-in messages are now dynamically generated by the LLM for each athlete, based on their training phase, recent load, and historical patterns — rather than fixed templates.",
    changes: [
      { tag: "new", text: "LLM-generated morning pulse questions personalized per athlete" },
      { tag: "new", text: "Railway cron job for automated daily check-in scheduling" },
      { tag: "new", text: "Coach pulse notification — coaches receive a summary digest of overnight check-ins" },
      { tag: "improved", text: "WhatsApp E.164 phone number normalization — improved delivery rates for international numbers" },
      { tag: "fix", text: "Resolved startup warning from missing environment variable validation" },
      { tag: "fix", text: "Fixed scheduler crash when athlete training phase was null" },
    ],
  },
  {
    version: "0.8.0",
    date: "April 2026",
    headline: "Athlete schema overhaul + send logs",
    summary: "We rebuilt the athlete data model to be more flexible and added full send-log tracking so coaches can see exactly what was sent, when, and to whom.",
    changes: [
      { tag: "new", text: "checkin_send_logs table — full audit trail of every outbound message" },
      { tag: "improved", text: "Athletes schema updated: added training_phase, goal_race, and wearable_connected fields" },
      { tag: "improved", text: "Scheduler now reads from the updated athletes schema correctly" },
      { tag: "fix", text: "Fixed duplicate send bug when scheduler retried failed WhatsApp deliveries" },
      { tag: "fix", text: "Resolved migration conflict between athletes and athlete_profiles tables" },
    ],
  },
  {
    version: "0.7.0",
    date: "March 2026",
    headline: "Full codebase security audit",
    summary: "A comprehensive security scan identified and resolved critical, medium, and low-severity issues across the API, auth layer, and data handling.",
    changes: [
      { tag: "fix", text: "Patched SQL injection vector in athlete search endpoint" },
      { tag: "fix", text: "Resolved unauthenticated route exposure in /api/athletes" },
      { tag: "fix", text: "Fixed insecure direct object reference in training plan retrieval" },
      { tag: "improved", text: "Added request rate limiting to all public endpoints" },
      { tag: "improved", text: "Hardened CORS policy — now allowlist-only" },
      { tag: "infrastructure", text: "Dockerfile CMD now handles startup — removed startCommand override" },
    ],
  },
  {
    version: "0.6.0",
    date: "February 2026",
    headline: "Voice calibration + draft approval flow",
    summary: "The core voice cloning pipeline is live. Coaches can now paste past WhatsApp replies during onboarding to build their personal voice model.",
    changes: [
      { tag: "new", text: "Voice calibration step in coach onboarding flow" },
      { tag: "new", text: "Draft approval UI — coaches see the generated reply, edit inline, and approve before sending" },
      { tag: "new", text: "Voice model stored per coach account — fully isolated, never shared" },
      { tag: "improved", text: "Draft generation latency reduced from ~8s to ~2.4s with streaming response" },
      { tag: "fix", text: "Fixed voice model overwrite bug when re-running calibration" },
    ],
  },
  {
    version: "0.5.0",
    date: "January 2026",
    headline: "WhatsApp Business API integration",
    summary: "First end-to-end WhatsApp message flow. Athletes can now send check-ins and receive coach replies via WhatsApp.",
    changes: [
      { tag: "new", text: "WhatsApp Business API webhook receiver" },
      { tag: "new", text: "Inbound message routing: athlete → check-in queue → coach dashboard" },
      { tag: "new", text: "Outbound message send from coach dashboard via WhatsApp Cloud API" },
      { tag: "infrastructure", text: "Railway deployment configured with persistent webhook endpoint" },
      { tag: "fix", text: "Resolved webhook signature validation failure on non-ASCII message bodies" },
    ],
  },
  {
    version: "0.4.0",
    date: "December 2025",
    headline: "Coach dashboard + athlete profiles",
    summary: "The main coach interface is live — roster view, athlete profile cards, and check-in history.",
    changes: [
      { tag: "new", text: "Coach dashboard: roster view with athlete status at a glance" },
      { tag: "new", text: "Athlete profile: training phase, goal race, recent check-ins" },
      { tag: "new", text: "Check-in history timeline per athlete" },
      { tag: "new", text: "Supabase auth integration — email/password login and session management" },
      { tag: "improved", text: "API response times on /athletes improved 3× with index optimization" },
    ],
  },
];

export default function ChangelogPage() {
  return (
    <MarketingShell>
      {/* Header */}
      <div style={{ background: LINEN_DEEP, borderBottom: `1px solid ${RULE}`, padding: "56px 32px" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <div style={{ fontFamily: MONO, fontSize: 10.5, letterSpacing: "0.18em", textTransform: "uppercase", color: TERRA_DEEP, marginBottom: 16 }}>Changelog</div>
          <h1 style={{ fontFamily: SERIF, fontSize: 52, fontWeight: 500, letterSpacing: "-0.015em", margin: "0 0 16px", color: INK }}>What&apos;s new in Andes.IA</h1>
          <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 19, lineHeight: 1.6, color: INK_SOFT, margin: 0 }}>
            Every release, improvement, and fix — documented as we ship.
          </p>
        </div>
      </div>

      {/* Releases */}
      <div style={{ maxWidth: 800, margin: "0 auto", padding: "64px 32px 96px" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
          {RELEASES.map((release, i) => (
            <div key={release.version} style={{ display: "grid", gridTemplateColumns: "180px 1fr", gap: 0 }}>
              {/* Left: version + date */}
              <div style={{ paddingTop: 4, paddingRight: 32, paddingBottom: i < RELEASES.length - 1 ? 56 : 0, position: "relative" }}>
                <div style={{ fontFamily: MONO, fontSize: 12, fontWeight: 600, letterSpacing: "0.08em", color: AEGEAN }}>{release.version}</div>
                <div style={{ fontFamily: MONO, fontSize: 10, letterSpacing: "0.12em", textTransform: "uppercase", color: INK_MUTE, marginTop: 4 }}>{release.date}</div>
                {i < RELEASES.length - 1 && (
                  <div style={{ position: "absolute", left: 0, top: 36, bottom: 0, width: 1, background: `linear-gradient(to bottom, ${RULE}, transparent)` }} />
                )}
              </div>

              {/* Right: release content */}
              <div style={{ borderLeft: `1px solid ${RULE}`, paddingLeft: 32, paddingBottom: i < RELEASES.length - 1 ? 56 : 0 }}>
                {/* Connector dot */}
                <div style={{ width: 10, height: 10, borderRadius: "50%", background: AEGEAN, border: `2px solid ${LINEN_DEEP}`, position: "relative", left: -37, top: 6, marginBottom: -10 }} />

                <h2 style={{ fontFamily: SERIF, fontSize: 28, fontWeight: 500, color: INK, margin: "0 0 8px" }}>{release.headline}</h2>

                {release.summary && (
                  <p style={{ fontFamily: BODY, fontSize: 14.5, color: INK_SOFT, lineHeight: 1.65, margin: "0 0 20px" }}>{release.summary}</p>
                )}

                <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                  {release.changes.map((change, j) => (
                    <div key={j} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
                      <div style={{ flexShrink: 0, marginTop: 2 }}>
                        <Tag type={change.tag} />
                      </div>
                      <span style={{ fontFamily: BODY, fontSize: 14, color: INK_SOFT, lineHeight: 1.55 }}>{change.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* End of log note */}
        <div style={{ borderTop: `1px solid ${RULE}`, marginTop: 48, paddingTop: 32, textAlign: "center" }}>
          <p style={{ fontFamily: SERIF, fontStyle: "italic", fontSize: 16, color: INK_MUTE, margin: 0 }}>
            Andes.IA is in active development. New releases ship frequently.
          </p>
          <p style={{ fontFamily: BODY, fontSize: 13.5, color: INK_MUTE, margin: "12px 0 0" }}>
            Questions about a release?{" "}
            <a href="mailto:felipeddeidan@gmail.com" style={{ color: AEGEAN, textDecoration: "none" }}>felipeddeidan@gmail.com</a>
          </p>
        </div>
      </div>
    </MarketingShell>
  );
}
